# Inspired by example Black config from https://github.com/psf/black#configuration-format
[tool.black]
line-length = 120
target-version = ['py36']
skip-string-normalization = true
exclude = '''
(
  /(
      \.git
    | \.circleci
    | \.devcontainer
    | \.localstack
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | venv
  )/
)
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = false
use_parentheses = true
known_first_party = 'test'
