# CircleCI DMP config
version: 2
jobs:
  build_image:
    docker:
      - image: circleci/python:3.6-jessie-node

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      # Install AWS CLI
      - run: sudo pip install awscli --upgrade

      - checkout

      # build and push Docker image
      - run: |
          export DOCKER_IMAGE_NAME=${DOCKER_PUSH_URL}:${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}
          echo ${DOCKER_IMAGE_NAME}
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
          eval $(aws ecr get-login --region us-west-2 --no-include-email)
          make push_image

  run_tests:
    machine:
      - image: circleci/python:3.6-jessie-node

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      # Install AWS CLI
      - run: sudo pip install awscli --upgrade

      - checkout

      - run : |
          export DOCKER_TAG_NAME_FULL=${DOCKER_PUSH_URL}:${CIRCLE_PREVIOUS_BUILD_NUM}-${CIRCLE_SHA1}
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
          eval $(aws ecr get-login --region us-west-2 --no-include-email)
          make test


workflows:
  version: 2
  build:
    jobs:
      - build_image

      - run_tests:
          requires:
            - build_image
