# CircleCI DMP config
version: 2
jobs:
  build_image:
    docker:
      - image: circleci/python:3.6-jessie-node

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          pip install awscli --upgrade --user
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
          make image
          make push_image

workflows:
  version: 2
  test:
    jobs:
      - build_image
