# CircleCI Data Collection config

version: 2

jobs:
  build_image:
    docker:
      - image: circleci/python:3.6-jessie-node

    environment:
      - DOCKER_PUSH_URL: "897117390337.dkr.ecr.us-east-1.amazonaws.com/operam/data-collection-fb"

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      # Install AWS CLI
      - run: sudo pip install awscli --upgrade

      - checkout

      # Setup workspace directory
      - run: mkdir -p /tmp/workspace

      # build and push Docker image & record data in workspace
      # Note that this will push 2 images, one tagged with the branch name and the other with the build ID
      - run: |
          export PUSH_IMAGE_NAME=${DOCKER_PUSH_URL}:${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)
          echo ${PUSH_IMAGE_NAME} > /tmp/workspace/image_url
          echo ${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD) > /tmp/workspace/image_name
          docker login -e aws+dockerci@operam.com -u operamci1 -p MZqvqD3zaPKQKoqpRDUDeFWd
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
          eval $(aws ecr get-login --region us-west-2 --no-include-email)
          make image
          make push_image
          PUSH_IMAGE_NAME=${DOCKER_PUSH_URL}:$(git rev-parse --abbrev-ref HEAD) make push_image

      # Persist the specified paths (workspace/image*) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be absolute path or relative path from working_directory
          root: /tmp/workspace
          # Must be relative path from root
          paths:
            - image_url
            - image_name

  run_tests:
    machine:
      image: circleci/classic:latest

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - checkout

      - run : |
          export IMAGE_NAME_FULL=`cat /tmp/workspace/image_url`
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
          eval $(aws ecr get-login --region us-west-2 --no-include-email)
          make test


workflows:
  version: 2
  build:
    jobs:
      - build_image

      - run_tests:
          requires:
            - build_image
