# CircleCI Data Collection config

version: 2

jobs:
  publish_image:
    docker:
      - image: circleci/python:3.6-jessie-node

    environment:
      - AWS_ACCOUNT_PROD: "583912811210"
      - AWS_ACCOUNT_STAGE: "897117390337"
      - AWS_ACCOUNT_ASSETS: "936368275341"
      - AWS_REGION: "us-east-1"

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      # Install AWS CLI
      - run: sudo pip install awscli --upgrade

      - checkout

      # Setup workspace directory
      - run: mkdir -p /tmp/workspace

      # For builds we use base images hosted at Docker Hub, private repo
      - run: |
          docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}

      # build and push Docker image
      # Note that this will push 2 images, one tagged with the branch name and the other with the build ID
      #
      # Long Term we are shifting to one, central image repository under Assets AWS account,
      # but for transitional reasons, still pushing to Prod and Stage AWS accounts too.
      - run: |
          export AWS_ACCOUNT=${AWS_ACCOUNT_ASSETS}
          eval $(aws ecr get-login --region ${AWS_REGION} --no-include-email --registry-ids ${AWS_ACCOUNT})
          export REPOSITORY_URL=${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/
          make push_image
          make print_image_name_build > /tmp/workspace/image_url

      # Remove this once deploy logic is fully adapted to Assets repos
      - run: |
          export AWS_ACCOUNT=${AWS_ACCOUNT_PROD}
          eval $(aws ecr get-login --region ${AWS_REGION} --no-include-email --registry-ids ${AWS_ACCOUNT})
          export REPOSITORY_URL=${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/
          make push_image

      # Remove this once deploy logic is fully adapted to Assets repos
      - run: |
          export AWS_ACCOUNT=${AWS_ACCOUNT_STAGE}
          eval $(aws ecr get-login --region ${AWS_REGION} --no-include-email --registry-ids ${AWS_ACCOUNT})
          export REPOSITORY_URL=${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/
          make push_image

  run_flake8:
    docker:
    - image: circleci/python:3.6-jessie-node
    steps:
    - checkout
    - run: sudo pip install -r requirements.dev.txt
    - run: flake8 --filename=*.py

  run_black:
    docker:
    - image: circleci/python:3.6-jessie-node
    steps:
    - checkout
    - run: sudo pip install -r requirements.dev.txt
    - run: black --skip-string-normalization --diff --line-length 120 --target-version py36 .

  run_tests:
    machine:
      image: circleci/classic:latest

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - checkout

      # Get the latest supported Docker Compose from Circle S3 repo & remove old copy
      # https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.6.4-jessie/Dockerfile#L60
      - run : |
          export COMPOSE_URL="https://circle-downloads.s3.amazonaws.com/circleci-images/cache/linux-amd64/docker-compose-latest"
          sudo rm -fr /usr/local/bin/docker-compose
          sudo curl --silent --show-error --location --fail --retry 3 --output /usr/bin/docker-compose $COMPOSE_URL
          sudo chmod +x /usr/bin/docker-compose

      - run : |
          export IMAGE_NAME_FULL=`cat /tmp/workspace/image_url`
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
          make test


workflows:
  version: 2
  build:
    jobs:
      - publish_image

      - run_tests:
          requires:
            - publish_image

      - run_flake8
      - run_black
