FROM alpine:3.4

# Install ruby first
RUN apk add --no-cache --update ruby

# Set which fake-s3 version you want
ARG FAKES3_VERSION=1.2.1
RUN gem install --no-document fakes3 -v ${FAKES3_VERSION}

# Put the files somewhere
RUN mkdir /s3_data

EXPOSE 4444

ENTRYPOINT ["fakes3", "-r", "/s3_data", "-p", "4444"]
