version: '2.3'

services:

  redis-cluster:
    extends:
      file: docker-compose-base.yaml
      service: redis-cluster

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  dynamo:
    extends:
      file: docker-compose-base.yaml
      service: dynamo

  fakes3:
    extends:
      file: docker-compose-base.yaml
      service: fakes3

#  dd-agent:
#    extends:
#      file: docker-compose-base.yaml
#      service: dd-agent

  app_default:
    scale: 8
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - fakes3
      - redis
      - dynamo
      - redis-cluster
    environment:
      APP_LOGGING_LEVEL: 'INFO'
#      APP_MEASUREMENT_STATSD_SERVER: 'dd-agent'
#    depends_on:
#      - dd-agent
    command: python app.py worker default

  app_flower:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - redis
    ports:
      - 5555:5555
    command: python app.py flower 5555
