version: '2.3'

services:

  redis-cluster:
    extends:
      file: docker-compose-base.yaml
      service: redis-cluster

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  dynamo:
    extends:
      file: docker-compose-base.yaml
      service: dynamo

  fakes3:
    extends:
      file: docker-compose-base.yaml
      service: fakes3

#  dd-agent:
#    extends:
#      file: docker-compose-base.yaml
#      service: dd-agent

  app:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - fakes3
      - redis
      - redis-cluster
      - dynamo
#    depends_on:
#      - dd-agent
    ports:
      - 5555:5555
    environment:
#      APP_MEASUREMENT_STATSD_SERVER: 'dd-agent'
      APP_LOGGING_LEVEL: 'INFO'
      APP_CELERY_task_eager_propagates: "true"
      APP_CELERY_task_always_eager: "true"
    command: bash

#    command: python app.py flower 5555
