version: '2'

services:

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  app:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - redis
    command: bash
