version: '2'

services:

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  collection:
    extends:
      file: docker-compose-base.yaml
      service: collection-system
    links:
      - redis
    command: celery worker --app=celery-entrypoint --pool gevent --autoscale=400,10
