version: '2.3'

services:

  redis-cluster:
    extends:
      file: docker-compose-base.yaml
      service: redis-cluster

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  dynamo:
    extends:
      file: docker-compose-base.yaml
      service: dynamo

  fakes3:
    extends:
      file: docker-compose-base.yaml
      service: fakes3

  app:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - fakes3
      - redis
      - redis-cluster
      - dynamo
      - dd-agent
    environment:
      APP_LOGGING_LEVEL: 'INFO'
      APP_CELERY_task_eager_propagates: "true"
      APP_CELERY_task_always_eager: "true"
    command: bash

  # Todo: fork this out into base for testing purposes
  dd-agent:
    image: datadog/docker-dd-agent:latest
    environment:
      DD_HOSTNAME: tomas-docker
      API_KEY: 887a5a65a5d2c1f71cd27c787dd9424c
      SD_BACKEND: docker

