version: '2'

services:

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  dynamo:
    extends:
      file: docker-compose-base.yaml
      service: dynamo

  app_longrunning:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - redis
      - dynamo
    command: python app.py worker longrunning

  app_default:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - redis
      - dynamo
    command: python app.py worker default
