version: '2.3'

services:

  redis-cluster:
    extends:
      file: docker-compose-base.yaml
      service: redis-cluster

  redis:
    extends:
      file: docker-compose-base.yaml
      service: redis

  dynamo:
    extends:
      file: docker-compose-base.yaml
      service: dynamo

  fakes3:
    extends:
      file: docker-compose-base.yaml
      service: fakes3

  app_longrunning:
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - fakes3
      - redis
      - dynamo
      - redis-cluster
#    environment:
#      # uncomment this to allow sweep looper to recurse back into sweep builder
#      APP_LOOPER_ALLOW_RECURSION: "true"
    command: python app.py worker longrunning

  app_default:
    scale: 2
    extends:
      file: docker-compose-base.yaml
      service: app
    links:
      - fakes3
      - redis
      - dynamo
      - redis-cluster
    command: python app.py worker default
